name: wh_ruletka
version: 1.0.0
main: me.whoyou.losowanie.Main
description: Plugin na ruletke z własnym systemem ekonomii.
api-version: 1.14

commands:
  bet:
    description: Zabetuj
    usage: /<command> [ilosc_coinsow] [czerwone|zielone|czarne]
    permission-message: Nie masz permisji!
  saldo:
    description: Zobacz swoje saldo
    usage: /<command>
    permission-message: Nie masz permisji!
  setcoins:
    description: Ustaw saldo graczu
    usage: /<command> [ilosc_coinsow] [nick_gracza]
    permission-message: Nie masz permisji!
  kup:
    description: Otwórz menu kupna
    usage: /<command>
    permission-message: Nie masz permisji!
  sprzedaj:
    description: Sprzedaj item
    usage: /<command>
    permission-message: Nie masz permisji!
  dosprzedania:
    description: Wyświetla listę itemów, które można sprzedać
    usage: /<command>
    permission-message: Nie masz permisji!